Market.Cqrsnes.WebUi/Controllers/OfferController.cs
using System;
using System.Web.Mvc;
using Cqrsnes.Infrastructure;
using Market.Cqrsnes.Domain.Commands;
using Market.Cqrsnes.Projection.Models;

namespace Market.Cqrsnes.WebUi.Controllers
{
    /// <summary>
    /// Hosts offer-related actions.
    /// </summary>
    public class OfferController : Controller
    {
        private readonly IBus bus;
        private readonly IRepository repository;
        private readonly ISystemContext context;

        /// <summary>
        /// Initializes a new instance of the <see cref="OfferController"/> class.
        /// </summary>
        /// <param name="bus">
        /// The bus.
        /// </param>
        /// <param name="repository">
        /// The repository.
        /// </param>
        /// <param name="context">The context.</param>
        public OfferController(IBus bus, IRepository repository, ISystemContext context)
        {
            this.bus = bus;
            this.repository = repository;
            this.context = context;
        }

        /// <summary>
        /// Lists offers.
        /// </summary>
        /// <returns>
        /// List of offers.
        /// </returns>
        public ActionResult List()
        {
            return View(repository.GetAll<Offer>());
        }

        /// <summary>
        /// Creates offer.
        /// </summary>
        /// <param name="storeId">
        /// The store id.
        /// </param>
        /// <param name="articleId">
        /// The article id.
        /// </param>
        /// <param name="count">
        /// The count.
        /// </param>
        /// <param name="price">
        /// The price.
        /// </param>
        /// <returns>
        /// Redirect to list of offers.
        /// </returns>
        [HttpPost]
        public ActionResult Create(Guid storeId, Guid articleId, int count, double price)
        {
            if (context.User.Id != repository.GetById<Store>(storeId).OwnerId)
            {
                throw new ApplicationException("Only owner can create the offer.");
            }

            bus.Send(new CreateOffer
                {
                    Id = Guid.NewGuid(),
                    StoreId = storeId,
                    ArticleId = articleId,
                    Count = count,
                    Price = price
                });

            return RedirectToAction("List");
        }

        /// <summary>
        /// Initiates purchase and redirects to list of offers.
        /// </summary>
        /// <param name="offerId">
        /// The offer id.
        /// </param>
        /// <param name="count">
        /// The count.
        /// </param>
        /// <returns>
        /// Redirect to list of offers.
        /// </returns>
        [HttpPost]
        public ActionResult Buy(Guid offerId, int count)
        {
            bus.Send(new BuyArticle
                {
                    OfferId = offerId,
                    Count = count,
                    BuyerId = context.User.Id
                });

            return RedirectToAction("List");
        }
    }
}

Market.Cqrsnes.WebUi/Controllers/StoreController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Cqrsnes.Infrastructure;
using Market.Cqrsnes.Domain.Commands;
using Market.Cqrsnes.Projection;
using Market.Cqrsnes.Projection.Models;
using Market.Cqrsnes.WebUi.Models;

namespace Market.Cqrsnes.WebUi.Controllers
{
    /// <summary>
    /// Hosts store-related actions.
    /// </summary>
    public class StoreController : Controller
    {
        private readonly IRepository repository;
        private readonly IBus bus;
        private readonly ISystemContext context;

        /// <summary>
        /// Initializes a new instance of the <see cref="StoreController"/> class.
        /// </summary>
        /// <param name="repository">
        /// The repository.
        /// </param>
        /// <param name="bus">
        /// The bus.
        /// </param>
        /// <param name="context">
        /// The context.
        /// </param>
        public StoreController(IRepository repository, IBus bus, ISystemContext context)
        {
            this.repository = repository;
            this.bus = bus;
            this.context = context;
        }

        /// <summary>
        /// Lists stores.
        /// </summary>
        /// <returns>
        /// List of stores.
        /// </returns>
        public ActionResult List()
        {
            return View(repository.GetAll<Store>());
        }

        /// <summary>
        /// Lists offers for given store.
        /// </summary>
        /// <param name="id">
        /// The id of store.
        /// </param>
        /// <returns>
        /// List of offers.
        /// </returns>
        public ActionResult Offers(Guid id)
        {
            return View(new StoreOffersViewModel
                {
                    Articles = repository.GetAll<Article>().Select(x => new SelectListItem
                        {
                            Text = x.Name,
                            Value = x.Id.ToString()
                        }).ToArray(),
                    StoreOffers = repository.GetById<StoreOffers>(id)
                });
        }

        /// <summary>
        /// Creates store.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <returns>
        /// Redirect to list of stores.
        /// </returns>
        [HttpPost]
        public ActionResult Create(string name)
        {
            bus.Send(new CreateStore
                {
                    Id = Guid.NewGuid(),
                    Name = name,
                    OwnerId = context.User.Id
                });

            return RedirectToAction("List");
        }
    }
}

Market.Cqrsnes.WebUi/Views/Store/List.cshtml
@using Market.Cqrsnes.WebUi
@model IEnumerable<Market.Cqrsnes.Projection.Models.Store>

@{
    ViewBag.Title = "Stores";
    ViewBag.Tagline = "here you can choose where to buy something";
}

@if (Model.Any())
{
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Owner</th>
                <th>Offers</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var store in Model)
            {
                <tr>
                    <td>@Html.ActionLink(store.Name, "Offers", new {id = store.Id})</td>
                    <td>@store.OwnerName</td>
                    <td>@store.OffersCount</td>
                </tr>
            }    
        </tbody>
    </table>
}
else
{
    <p>There are no stores yet.</p>
}

<form action="@Url.Action("Create")" method="POST">
    <div class="clearfix">
        <label for="name">Name:</label>
        <div class="input">
            <input type="text" id="name" name="name"/>
            <button class="btn" type="submit">Create new</button>
        </div>
    </div>
</form>

Market.Cqrsnes.WebUi/Views/Store/Offers.cshtml
@using Market.Cqrsnes.Projection
@using Market.Cqrsnes.WebUi
@model Market.Cqrsnes.WebUi.Models.StoreOffersViewModel

@{
    ViewBag.Title = "Offers";
    ViewBag.Tagline = string.Format("what is proposed by {0}", Model.StoreOffers.Name);
}

@if (Model.StoreOffers.Offers.Any())
{
    <table>
        <thead>
            <tr>
                <th>Article</th>
                <th>Price</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.StoreOffers.Offers)
            {
                <tr>
                    <td>@item.ArticleName</td>
                    <td>@item.Price</td>
                    <td>@item.Count</td>
                </tr>
            }    
        </tbody>
    </table>
}
else
{
    <p>There are no offers yet.</p>
}

@if (WebApplication.SystemContext.User.Id == Model.StoreOffers.OwnerId)
{
    <br/>

    <form action="@Url.Action("Create", "Offer")" method="POST">
        <input type="hidden" name="StoreId" value="@Model.StoreOffers.Id"/>
        <div class="clearfix">
            <label for="articleId">Article:</label>
            <div class="input">
                @Html.DropDownList("articleId", Model.Articles)
            </div>
        </div>
        <div class="clearfix">
            <label for="price">Price:</label>
            <div class="input">
                <input type="text" id="price" class="input-small" name="price"/>
            </div>
        </div>
        <div class="clearfix">
            <label for="count">Count:</label>
            <div class="input">
                <input type="text" id="count" class="input-small" name="count"/>
                <button class="btn" type="submit">Create new</button>
            </div>
        </div>
    </form>
}